In [13]:
# Импорт numpy
import numpy as np

In [15]:
# Создание массива
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 7, 1, 5, 2])
print(arr)

[1 2 3 4 5]


In [16]:
arr_zeros = np.zeros((2, 3)) # создаст матрицу 2x3 из нулей
arr_ones = np.ones((3, 2)) # создаст матрицу 3x2 из единиц
arr_arange = np.arange(0, 10, 2) # аналог range
print(arr_zeros, arr_ones, arr_arange)

[[0. 0. 0.]
 [0. 0. 0.]] [[1. 1.]
 [1. 1.]
 [1. 1.]] [0 2 4 6 8]


In [17]:
arr_shape = arr_arange.shape # форма матрицы
arr_dtype = arr_arange.dtype # тип данных 
print(arr_shape, arr_dtype)

(5,) int64


In [18]:
# Элемент через индекс
single = arr[2]
print(single)

3


In [19]:
# Срез массива
sub_arr = arr[1:4]
print(sub_arr)

[2 3 4]


In [20]:
# Векторные операции
vec_sum = arr + arr2
vec_mul = arr * arr2
print(vec_sum, vec_mul)

[5 9 4 9 7] [ 4 14  3 20 10]


In [21]:
# Вычисление средней величины
mean_value = arr.mean()
print(mean_value)

3.0
